
"""
Global constants for the Risk Missions Simulator.
"""

GAME_NAME = "Risk Missions Simulator"
VERSION = "0.1.0"

PLAYER_COUNT = 3
NEUTRAL_COUNT = 3
FACTION_COUNT = PLAYER_COUNT + NEUTRAL_COUNT

TERRITORY_COUNT = 42
CONTINENT_COUNT = 6

STARTING_TERRITORIES = 7
STARTING_ARMIES = 21

PRIVATE_MISSIONS = 3
PUBLIC_MISSIONS = 3
TOTAL_MISSIONS = 12

WINNING_POINTS = 4

MAX_ATTACK_DICE = 3
MAX_DEFEND_DICE = 2
